### ISSUE TITLE
uninitialized constant WillPaginate::ActionView::LinkRenderer (NameError)

### ISSUE THREAD

**Issue by jmgarnier** [xdite/bootstrap-helper#12]
When starting server, an exception is raised:

.rvm/gems/ruby-1.9.3-p194@/gems/bootstrap_helper-2.1.0/config/initializers/will_paginate.rb:10:in `<module:ActionView>': uninitialized constant WillPaginate::ActionView::LinkRenderer (NameError)
    from /.rvm/gems/ruby-1.9.3-p194@/gems/bootstrap_helper-2.1.0/config/initializers/will_paginate.rb:4:in`module:WillPaginate'
    from/.rvm/gems/ruby-1.9.3-p194@/gems/bootstrap_helper-2.1.0/config/initializers/will_paginate.rb:3:in `<top (required)>'
    from /.rvm/gems/ruby-1.9.3-p194@/gems/railties-3.2.6/lib/rails/engine.rb:588:in`block (2 levels) in class:Engine'

https://gist.github.com/1214011/7ffaa86636e5b5b1fe872f9273834373c58f7ab6 should solve the bug

**Comment by xdite** [comment]
fixed?
