### ISSUE TITLE
Will_paginate dependency

### ISSUE THREAD

**Issue by billsaysthis** [xdite/bootstrap-helper#4]
I'm not familiar with how this is supposed to be implemented but putting bootstrap_helper in my Gemfile is not sufficient to get will_paginate installed. Instead if I run rake -T I get this error:

```
no such file to load -- will_paginate/view_helpers/link_renderer
```

Not clear why the gem has this dependency though, maybe it can be removed or at least don't be so specific in required verion?

```
j3: gem list will

*** LOCAL GEMS ***


j3: gem inst will_paginate
Fetching: will_paginate-3.0.2.gem (100%)
Successfully installed will_paginate-3.0.2
1 gem installed
j3: rake -T db            
rake aborted!
no such file to load -- will_paginate/view_helpers/link_renderer

(See full trace by running task with --trace)
j3: gem list will

*** LOCAL GEMS ***

will_paginate (3.0.2)
```

**Comment by xdite** [comment]
added
