### ISSUE TITLE
README-Error link

### ISSUE THREAD

**Issue by BoZhuM** [xdite/bootstrap-helper#7]
You have renamed your gem 'bootstrap_helper' to 'bootstrap-helper', But There is a url link to the old gem:
`see example`
The example link link to https://github.com/xdite/bootstrap_helper/tree/master/example/application.html.erb
You should link to https://github.com/xdite/bootstrap-helper/blob/master/example/application.html.erb.
is it right?

**Comment by xdite** [comment]
thanks

**Comment by xdite** [comment]
done
